config/routes.rb
Rails.application.routes.draw do
  get 'gardener_plants/create'
  get '/', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :gardens, only: [:show] do
  	
  	resources :plants, only: [:create]
  
  end


  resources :plants, only: [:destroy, :show] do
	  resources :gardener_plants, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
	has_many :plants, dependent: :destroy
end

app/models/gardener.rb
class Gardener < ApplicationRecord
end

app/models/gardener_plant.rb
class GardenerPlant < ApplicationRecord
  belongs_to :gardener
  belongs_to :plant
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  has_many :gardener_plants
  has_many :gardeners, through: :gardener_plants

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardener_plants_controller.rb
class GardenerPlantsController < ApplicationController
  def create
  	@plant = Plant.find(params[:plant_id])

    params[:gardener_plant][:gardener_id].each do |gardener_id|
      @gardener_plant = GardenerPlant.new(gardener_id: gardener_id)
      @gardener_plant.plant = @plant
      @gardener_plant.save
    end
  	redirect_to @plant
  end

  def gardener_plant_params
  	params.require(:gardener_plant).permit(:gardener_id)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def show
  	@garden = Garden.find(params[:id])
  	@plant = Plant.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :destroy]

  def create
  	@plant = Plant.new(plant_params)
  	@garden = Garden.find(params[:garden_id])
  	@plant.garden = @garden

  	if @plant.save
  		redirect_to @garden, notice: 'Youve created a plant'
  	else 
      flash[:alert] = 'Couldnt create'
  		render template: 'gardens/show'
  	end
  end

  def destroy
  	@plant.destroy
  	redirect_to @plant.garden
  end

  def show
    @gardener_plant = GardenerPlant.new
  end

  def set_plant
    @plant = Plant.find(params[:id])
  end

  def plant_params
  	params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardener_plants_helper.rb
module GardenerPlantsHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardener_plants/create.html.erb
<h1>GardenerPlants#create</h1>
<p>Find me in app/views/gardener_plants/create.html.erb</p>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container">
	<div class="row mt-4">
		<% @garden.plants.each do |plant| %>
			<div class="col-4 my-2">
				<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
				  <%= plant.name %>

				  <%= link_to plant_path(plant), method: :delete, class: 'btn btn-danger card-button' do %>
						<i class="fas fa-trash"></i>
				  <% end %>
				</div>
				<%= link_to 'See Plant', plant_path(plant), class: 'btn btn-primary' %>
			</div>
		<% end %>
	</div>

	<div class="row justify-content-center my-5">
		<div class="col-6 p-5 rounded border bg-white">
			<%= simple_form_for [@garden, @plant] do |f| %>
				<%= f.input :name %>
				<%= f.input :image_url %>
				<%= f.submit 'Save Plant', class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGardener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/alerts' %>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container py-5">
	<div class="row justify-content-center">
		<div class="col-6">
			<h1>🌳The Gardener🌳</h1>
			<hr>
			<br>
			<h3>User Stories:</h3>
			<ul>
				<li><code>As a user I can see one garden's plants</code></li>
				<li><code>As a user I can add a plant in a garden</code></li>
				<li><code>As a user I can delete a plant</code></li>
			</ul>
			<br>
			<h3>Gardens:</h3>
			<ul>
				<li>can have many plants</li>
				<li>has a name</li>
				<li>has a banner</li>
			</ul>

			<br>

			<h3>Plants:</h3>
			<ul>
				<li>belongs to a garden</li>
				<li>has a name</li>
				<li>has a name image</li>
			</ul>	
		</div>
	</div>
</div>

app/views/plants/create.html.erb
<h1>Plants#create</h1>
<p>Find me in app/views/plants/create.html.erb</p>

app/views/plants/destroy.html.erb
<h1>Plants#destroy</h1>
<p>Find me in app/views/plants/destroy.html.erb</p>

app/views/plants/show.html.erb
<div class="container my-5">
	<h1><%= @plant.name %></h1>

	<% @plant.gardeners.each do |gardener| %>
		<p><%= gardener.name %></p>
	<% end %>

	<%= simple_form_for [@plant, @gardener_plant] do |f| %>
		<%= f.association :gardener, input_html: { multiple: true, class: 'multiple-select' }, include_hidden: false %>
		<%= f.submit :Save %>
	<% end %>
</div>

app/views/shared/_alerts.html.erb
<% if alert %>
	<div class="flash flash-danger alert alert-dismissible fade show" role="alert">
	  <span><%= alert %></span>
	  <a data-dismiss="alert" aria-label="Close">
	    <i class="fas fa-times"></i>
	  </a>
	</div>	
<% end %>

<% if notice %>
	<div class="flash flash-success alert alert-dismissible fade show" role="alert">
	  <span><%= notice %></span>
	  <a data-dismiss="alert" aria-label="Close">
	    <i class="fas fa-times"></i>
	  </a>
	</div>	
<% end %>